export * from "./Homepage";
export * from "./About";
export * from "./Portfolio";
export * from "./Reviews";
export * from "./Contacts";
export * from "./Admin/Admin";
export * from "./Admin/Projects";
export * from "./Admin/Technologies";
export * from "./Admin/Reviews";
