export * from "./Homepage";
export * from "./About";
export * from "./Portfolio";
export * from "./Reviews";
export * from "./Contacts";
export * from "./admin/Admin";
export * from "./admin/Projects";
export * from "./admin/Technologies";
export * from "./admin/Reviews";
export * from "./Project"
